### ISSUE TITLE
Build Error on OS X 10.11.6: candidate function has been explicitly made unavailable     constexpr value_type const& value() const

### ISSUE THREAD

**Issue by dbl001** [HiroakiMikami/deep-coder#25]
I have a 'make' build error: 

``` $g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
David-Laxers-MacBook-Pro:build davidlaxer$ cmake --version
cmake version 3.9.1
```

```
$ make
Scanning dependencies of target deepcoder
[  3%] Building CXX object lib/CMakeFiles/deepcoder.dir/attribute.cc.o
/Users/davidlaxer/deep-coder/lib/attribute.cc:48:58: error: call to unavailable
      member function 'value':
                this->predicate_presence[arg.predicate().value()] = 1;
                                         ~~~~~~~~~~~~~~~~^~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/experimental/optional:525:17: note: 
      candidate function has been explicitly made unavailable
    value_type& value()
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/experimental/optional:517:33: note: 
      candidate function has been explicitly made unavailable
    constexpr value_type const& value() const
                                ^
/Users/davidlaxer/deep-coder/lib/attribute.cc:50:78: error: call to unavailable
      member function 'value':
  ...this->one_argument_lambda_presence[arg.one_argument_lambda().value()] = 1;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/experimental/optional:525:17: note: 
      candidate function has been explicitly made unavailable
    value_type& value()
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/experimental/optional:517:33: note: 
      candidate function has been explicitly made unavailable
    constexpr value_type const& value() const
                                ^
/Users/davidlaxer/deep-coder/lib/attribute.cc:52:80: error: call to unavailable
      member function 'value':
  ...this->two_arguments_lambda_presence[arg.two_arguments_lambda().value()] ...
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/experimental/optional:525:17: note: 
      candidate function has been explicitly made unavailable
    value_type& value()
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/experimental/optional:517:33: note: 
      candidate function has been explicitly made unavailable
    constexpr value_type const& value() const
                                ^
3 errors generated.
make[2]: *** [lib/CMakeFiles/deepcoder.dir/attribute.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/deepcoder.dir/all] Error 2
make: *** [all] Error 2
```

Is this issue related?

https://stackoverflow.com/questions/44217316/how-do-i-use-stdoptional-in-c

**Comment by HiroakiMikami** [comment]
Thank you for reporting the issue.

I think [the StackOverflow post](https://stackoverflow.com/questions/44217316/how-do-i-use-stdoptional-in-c) you mentioned is related.
I can't reproduce the build error because I don't have OS X machine. But I think that you can solve the error using the same workaround.

**Comment by dbl001** [comment]
Yes, I saw the StackOverflow post.

I tried building deep-coder on Ubuntu 14.04 LTS with g++ 6.3.0

ubuntu@ip-10-0-1-107:~/deep-coder/build$ g++ --version
g++ (Ubuntu/Linaro 6.3.0-18ubuntu2~14.04) 6.3.0 20170519
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR 

I’m having an issue with ‘find_if’.  I also tried: std::find_if.
Any ideas?


ubuntu@ip-10-0-1-107:~/deep-coder$ mkdir -p build
ubuntu@ip-10-0-1-107:~/deep-coder$ cd build
ubuntu@ip-10-0-1-107:~/deep-coder/build$ cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GTest: /usr/lib/libgtest.a  
/home/ubuntu/deep-coder/build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/deep-coder/build
ubuntu@ip-10-0-1-107:~/deep-coder/build$ make
Scanning dependencies of target deepcoder
[  4%] Building CXX object lib/CMakeFiles/deepcoder.dir/attribute.cc.o
[  9%] Building CXX object lib/CMakeFiles/deepcoder.dir/find-program.cc.o
[ 14%] Building CXX object lib/CMakeFiles/deepcoder.dir/dataset-generator.cc.o
[ 19%] Building CXX object lib/CMakeFiles/deepcoder.dir/dsl/ast.cc.o
[ 23%] Building CXX object lib/CMakeFiles/deepcoder.dir/dsl/interpreter.cc.o
[ 28%] Building CXX object lib/CMakeFiles/deepcoder.dir/dsl/type.cc.o
[ 33%] Building CXX object lib/CMakeFiles/deepcoder.dir/dsl/utils.cc.o
[ 38%] Building CXX object lib/CMakeFiles/deepcoder.dir/example-generator.cc.o
Linking CXX static library libdeepcoder.a
[ 38%] Built target deepcoder
Scanning dependencies of target test-deep-coder
[ 42%] Building CXX object test/CMakeFiles/test-deep-coder.dir/main.cc.o
[ 47%] Building CXX object test/CMakeFiles/test-deep-coder.dir/enumerator-test.cc.o
In file included from /usr/include/gtest/gtest.h:57:0,
                 from /home/ubuntu/deep-coder/test/enumerator-test.cc:1:
/home/ubuntu/deep-coder/test/enumerator-test.cc: In member function ‘virtual void EnumerateTest_EnumerateFunctionTest_Test::TestBody()’:
/home/ubuntu/deep-coder/test/enumerator-test.cc:25:17: error: ‘find_if’ is not a member of ‘std’
     EXPECT_TRUE(std::find_if(ps.begin(), ps.end(), [](const Program& p) -> bool {
                 ^
/home/ubuntu/deep-coder/test/enumerator-test.cc: In member function ‘virtual void EnumerateTest_EnumerateArgumentsTest_Test::TestBody()’:
/home/ubuntu/deep-coder/test/enumerator-test.cc:48:6: error: ‘find_if’ was not declared in this scope
     }) != ps.end());
      ^
/home/ubuntu/deep-coder/test/enumerator-test.cc: In member function ‘virtual void EnumerateTest_EnumerateLambdaTest_Test::TestBody()’:
/home/ubuntu/deep-coder/test/enumerator-test.cc:70:6: error: ‘find_if’ was not declared in this scope
     }) != ps.end());
      ^
/home/ubuntu/deep-coder/test/enumerator-test.cc:74:6: error: ‘find_if’ was not declared in this scope
     }) != ps.end());
      ^
make[2]: *** [test/CMakeFiles/test-deep-coder.dir/enumerator-test.cc.o] Error 1
make[1]: *** [test/CMakeFiles/test-deep-coder.dir/all] Error 2
make: *** [all] Error 2
ubuntu@ip-10-0-1-107:~/deep-coder/build$

**Comment by HiroakiMikami** [comment]
I'm sorry about my mistake in `enumerator-test.cc` (I forgot to add `#include <algorithm>`).
The latest master branch fixed this issue. And I tested that it can be compiled with g++-6.3.0 and Ubuntu 14.04 in AWS EC2.

Alternatively, because `enumerator-test.cc` is a unit test files, these errors can be ignored by `echo > test/CMakeLists.txt`.

**Comment by dbl001** [comment]
Thanks!

Which version of ‘gtest’ do I need?

E.g. -

[ 52%] Building CXX object test/CMakeFiles/test-deep-coder.dir/example-generator-test.cc.o
In file included from /usr/include/gtest/gtest.h:57:0,
                 from /home/ubuntu/deep-coder/test/example-generator-test.cc:2:
/home/ubuntu/deep-coder/test/example-generator-test.cc: In member function ‘virtual void GenerateListTest_MinMaxLengthTest_Test::TestBody()’:
/home/ubuntu/deep-coder/test/example-generator-test.cc:85:9: error: no matching function for call to ‘testing::AssertionResult::AssertionResult(std::experimental::fundamentals_v1::optional<std::vector<int> >&)’
         EXPECT_TRUE(x);
         ^
In file included from /home/ubuntu/deep-coder/test/example-generator-test.cc:2::
/usr/include/gtest/gtest.h:271:12: note: candidate: testing::AssertionResult::AssertionResult(bool)
   explicit AssertionResult(bool success) : success_(success) {}
            ^~~~~~~~~~~~~~~
/usr/include/gtest/gtest.h:271:12: note:   no known conversion for argument 1 from ‘std::experimental::fundamentals_v1::optional<std::vector<int> >’ to ‘bool’
/usr/include/gtest/gtest.h:269:3: note: candidate: testing::AssertionResult::AssertionResult(const testing::AssertionResult&)
   AssertionResult(const AssertionResult& other);
   ^~~~~~~~~~~~~~~
/usr/include/gtest/gtest.h:269:3: note:   no known conversion for argument 1 from ‘std::experimental::fundamentals_v1::optional<std::vector<int> >’ to ‘const testing::AssertionResult&’
In file included from /usr/include/gtest/gtest.h:57:0,
                 from /home/ubuntu/deep-coder/test/example-generator-test.cc:2:
/home/ubuntu/deep-coder/test/example-generator-test.cc: In member function ‘virtual void GenerateListTest_IntegerConstraintTest_Test::TestBody()’:
/home/ubuntu/deep-coder/test/example-generator-test.cc:105:9: error: no matching function for call to ‘testing::AssertionResult::AssertionResult(std::experimental::fundamentals_v1::optional<std::vector<int> >&)’
         EXPECT_TRUE(x);
         ^
In file included from /home/ubuntu/deep-coder/test/example-generator-test.cc:2::
/usr/include/gtest/gtest.h:271:12: note: candidate: testing::AssertionResult::AssertionResult(bool)
   explicit AssertionResult(bool success) : success_(success) {}
            ^~~~~~~~~~~~~~~
/usr/include/gtest/gtest.h:271:12: note:   no known conversion for argument 1 from ‘std::experimental::fundamentals_v1::optional<std::vector<int> >’ to ‘bool’
/usr/include/gtest/gtest.h:269:3: note: candidate: testing::AssertionResult::AssertionResult(const testing::AssertionResult&)
   AssertionResult(const AssertionResult& other);
   ^~~~~~~~~~~~~~~
/usr/include/gtest/gtest.h:269:3: note:   no known conversion for argument 1 from ‘std::experimental::fundamentals_v1::optional<std::vector<int> >’ to ‘const testing::AssertionResult&’
In file included from /usr/include/gtest/gtest.h:57:0,
                 from /home/ubuntu/deep-coder/test/example-generator-test.cc:2:
/home/ubuntu/deep-coder/test/example-generator-test.cc: In member function ‘virtual void AnalyzeTest_SimpleAnalyzeTest_Test::TestBody()’:
/home/ubuntu/deep-coder/test/example-generator-test.cc:130:5: error: no matching function for call to ‘testing::AssertionResult::AssertionResult(std::experimental::fundamentals_v1::optional<Constraint>&)’
     EXPECT_TRUE(c);
     ^
In file included from /home/ubuntu/deep-coder/test/example-generator-test.cc:2::
/usr/include/gtest/gtest.h:271:12: note: candidate: testing::AssertionResult::AssertionResult(bool)
   explicit AssertionResult(bool success) : success_(success) {}
            ^~~~~~~~~~~~~~~
/usr/include/gtest/gtest.h:271:12: note:   no known conversion for argument 1 from ‘std::experimental::fundamentals_v1::optional<Constraint>’ to ‘bool’
/usr/include/gtest/gtest.h:269:3: note: candidate: testing::AssertionResult::AssertionResult(const testing::AssertionResult&)
   AssertionResult(const AssertionResult& other);
   ^~~~~~~~~~~~~~~
/usr/include/gtest/gtest.h:269:3: note:   no known conversion for argument 1 from ‘std::experimental::fundamentals_v1::optional<Constraint>’ to ‘const testing::AssertionResult&’
In file included from /usr/include/gtest/gtest.h:57:0,
                 from /home/ubuntu/deep-coder/test/example-generator-test.cc:2:
/home/ubuntu/deep-coder/test/example-generator-test.cc:136:5: error: no matching function for call to ‘testing::AssertionResult::AssertionResult(std::experimental::fundamentals_v1::optional<int>&)’
     EXPECT_TRUE(c.value().integer_variables.find(1)->second.min);
     ^
In file included from /home/ubuntu/deep-coder/test/example-generator-test.cc:2::
/usr/include/gtest/gtest.h:271:12: note: candidate: testing::AssertionResult::AssertionResult(bool)
   explicit AssertionResult(bool success) : success_(success) {}
            ^~~~~~~~~~~~~~~
/usr/include/gtest/gtest.h:271:12: note:   no known conversion for argument 1 from ‘std::experimental::fundamentals_v1::optional<int>’ to ‘bool’
/usr/include/gtest/gtest.h:269:3: note: candidate: testing::AssertionResult::AssertionResult(const testing::AssertionResult&)
   AssertionResult(const AssertionResult& other);
   ^~~~~~~~~~~~~~~
/usr/include/gtest/gtest.h:269:3: note:   no known conversion for argument 1 from ‘std::experimental::fundamentals_v1::optional<int>’ to ‘const testing::AssertionResult&’
In file included from /usr/include/gtest/gtest.h:57:0,
                 from /home/ubuntu/deep-coder/test/example-generator-test.cc:2:
/home/ubuntu/deep-coder/test/example-generator-test.cc: In member function ‘virtual void GenerateExamplesTest_SimpleGenerationTest_Test::TestBody()’:
/home/ubuntu/deep-coder/test/example-generator-test.cc:152:9: error: no matching function for call to ‘testing::AssertionResult::AssertionResult(std::experimental::fundamentals_v1::optional<std::vector<Example> >&)’
         EXPECT_TRUE(examples);
         ^
In file included from /home/ubuntu/deep-coder/test/example-generator-test.cc:2::
/usr/include/gtest/gtest.h:271:12: note: candidate: testing::AssertionResult::AssertionResult(bool)
   explicit AssertionResult(bool success) : success_(success) {}
            ^~~~~~~~~~~~~~~
/usr/include/gtest/gtest.h:271:12: note:   no known conversion for argument 1 from ‘std::experimental::fundamentals_v1::optional<std::vector<Example> >’ to ‘bool’
/usr/include/gtest/gtest.h:269:3: note: candidate: testing::AssertionResult::AssertionResult(const testing::AssertionResult&)
   AssertionResult(const AssertionResult& other);
   ^~~~~~~~~~~~~~~
/usr/include/gtest/gtest.h:269:3: note:   no known conversion for argument 1 from ‘std::experimental::fundamentals_v1::optional<std::vector<Example> >’ to ‘const testing::AssertionResult&’
make[2]: *** [test/CMakeFiles/test-deep-coder.dir/example-generator-test.cc.o] Error 1
make[1]: *** [test/CMakeFiles/test-deep-coder.dir/all] Error 2
make: *** [all] Error 2
ubuntu@ip-10-0-1-107:~/deep-coder/build$

**Comment by HiroakiMikami** [comment]
Now I cannot check the gtest version because the AWS instance was already terminated.
But I fixed these errors by adding `static_cast<bool>(...)` to `EXPECT_TRUE` and `EXPECT_FALSE` macros.

Would you use the master (`b11a07d4d2113f69d`)? This commit was checked with g++-6.3.0 and gtest 1.8.0-1 in Arch Linux.

Thank you.

**Comment by dbl001** [comment]
Thank You!

The programs are working on Linux.
I’ll investigate getting them to work on OS X.

**Comment by dbl001** [comment]
Generating the large dataset failed:
 $ ./build/src/gen_dataset 4 8000000 400 2>&1 > dataset.json


Progress: 7997600 / 8000000
Progress: 8007200 / 8000000
Killed

This one worked:

$ ./build/src/gen_dataset 4 1000000 400 2>&1 > dataset.json

-rw-rw-r-- 1 ubuntu ubuntu 402625483 Sep  5 17:36 dataset.json

Any ideas on what killed ‘gen_dataset’ before it could output ‘dataset.json’?

This is running on Ubuntu 14.04 LTS on EC2.

**Comment by dbl001** [comment]
And this in in learner.py using Chainer (CPU) …


(myenv) ubuntu@ip-10-0-1-107:~/deep-coder$ python3 ./python/learner.py dataset.json model.dat
0.001 100 100
Data set size: 1015200
Traceback (most recent call last):
  File "./python/learner.py", line 83, in <module>
    trainer.run()
  File "/home/ubuntu/anaconda/envs/myenv/lib/python3.4/site-packages/chainer/training/trainer.py", line 296, in run
    update()
  File "/home/ubuntu/anaconda/envs/myenv/lib/python3.4/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/ubuntu/anaconda/envs/myenv/lib/python3.4/site-packages/chainer/training/updater.py", line 228, in update_core
    in_arrays = self.converter(batch, self.device)
  File "/home/ubuntu/anaconda/envs/myenv/lib/python3.4/site-packages/chainer/dataset/convert.py", line 93, in concat_examples
    [example[i] for example in batch], padding[i])))
  File "/home/ubuntu/anaconda/envs/myenv/lib/python3.4/site-packages/chainer/dataset/convert.py", line 123, in _concat_arrays
    return xp.concatenate([array[None] for array in arrays])
ValueError: all the input array dimensions except for the concatenation axis must match exactly
